# Generated by Django 2.0.3 on 2018-03-14 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='areaUsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('folio', models.IntegerField(primary_key=True, serialize=False)),
                ('Remitente', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('numHojas', models.IntegerField()),
                ('anexos', models.IntegerField()),
                ('fechaExpiracion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('anexos', models.FileField(upload_to='archivosenviados/%Y')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePri', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(max_length=1000)),
                ('fecharespuesta', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Envio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mame', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameArea', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='respuesta',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Usuario'),
        ),
        migrations.AddField(
            model_name='envio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Usuario'),
        ),
        migrations.AddField(
            model_name='documento',
            name='namePri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Prioridad'),
        ),
        migrations.AddField(
            model_name='documento',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Usuario'),
        ),
        migrations.AddField(
            model_name='areausr',
            name='nameArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Zona'),
        ),
        migrations.AddField(
            model_name='areausr',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Usuario'),
        ),
    ]
