# Generated by Django 2.0.3 on 2018-03-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namearea', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='areaUsr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('folio', models.IntegerField(primary_key=True, serialize=False)),
                ('sender', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('numshet', models.IntegerField()),
                ('numann', models.IntegerField()),
                ('fechaexp', models.DateTimeField()),
                ('dateexp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Importan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namepri', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(max_length=1000)),
                ('fecharespuesta', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('annexes', models.FileField(upload_to='archivosenviados/')),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameusr', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='sending',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Usuario'),
        ),
        migrations.AddField(
            model_name='reply',
            name='update_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Usuario'),
        ),
        migrations.AddField(
            model_name='document',
            name='importancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Importan'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Usuario'),
        ),
        migrations.AddField(
            model_name='areausr',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Usuario'),
        ),
    ]
