# Generated by Django 2.0.3 on 2018-03-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180319_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fechaexp',
        ),
    ]
