# Generated by Django 2.0.3 on 2018-04-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20180409_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
