# Generated by Django 2.0.3 on 2018-04-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20180410_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='user',
        ),
        migrations.AddField(
            model_name='sending',
            name='user',
            field=models.ManyToManyField(blank=True, to='files.Usuario'),
        ),
    ]
