# Generated by Django 2.0.3 on 2018-04-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20180423_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='annexes',
            field=models.FileField(blank=True, null=True, upload_to='archivosenviados/%Y/%m/%d'),
        ),
    ]
