# Generated by Django 2.0.3 on 2018-05-08 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20180423_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sending',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
